contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://glendc.com"
canonifyurls = true
languageCode = "en-us"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  name = "Glen De Cauwsemaecker"
  description = "personal website of Glen De Cauwsemaecker"
  author = "Glen De Cauwsemaecker"
  email = "contact@glendc.com"

  [params.navigation]
    brand = "Glen DC"


  [params.header]
    # Copy your own image into './static/img/'' if you wish
    image = "frisbee.png"
    name = "Glen DC"
    subtitle = "Blogger - Hacker - Nomad"


  [params.portfolio]
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfolio"

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttontext = "Close"


  [params.about]
    title = "About"
    # The about text is splitted into a left and right column
    left = "I’m a hacker who loves challenges and I'm always willing to learn and improve. Growing up with technology, my hunger for knowledge and persuasive personality made me the person I am today."
    right = "Open source, free education and a global world are what I stand for. Feel free to contact me for questions and proposals."

    [params.about.button]
      text = "Download CV"
      link = "http://glendc.com/files/resume.pdf"
      icon = "download"


  [params.contact]
    title = "Contact"

    # 'error' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Name"
      error = "Please enter your name."

    [params.contact.form.email]
      text = "Email Adress"
      error = "Please enter your email address."

    [params.contact.form.phone]
      text = "Phone Number"
      error = "Please enter your phone number."

    [params.contact.form.message]
      text = "Message"
      error = "Please enter a message."

    [params.contact.form.button]
      text = "Send"


  [params.footer]
    copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

    [params.footer.location]
      title = "Current Location"
      # Postal address (add as many lines as necessary)
      address = ["United Kingdom"]

    [params.footer.social]
      title = "Around the web"
      # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
      # for more icons. The icons are represented by their corresponding
      # CSS class.
      [[params.footer.social.networks]]
        icon = "fa-github"
        link = "//github.com/GlenDC"

      [[params.footer.social.networks]]
        icon = "fa-twitter"
        link=  "//twitter.com/ORPH4NUS"

      [[params.footer.social.networks]]
        icon = "fa-linkedin"
        link=  "//uk.linkedin.com/pub/glen-de-cauwsemaecker/35/37b/964"

    [params.footer.credits]
        title = "Credits"
        text = "Generated with [Hugo](https://gohugo.io/), themified based on [Freelance](https://github.com/digitalcraftsman/hugo-freelancer-theme), source hosted on [GitHub](github.com/GlenDC/glendc-go)."